yaaa_version: 0.5

imports:
  - ExampleInterfaces.interfaces

input_ports: []

output_ports:
  - name: output
    type: Message

internal_state:
  cpp_type: example::InternalState
  cpp_include: example_runnables/internal_state.hpp
