yaaa_version: 0.5

imports:
  - Message.interfaces

input_ports: []

output_ports:
  - name: output
    type: Message

internal_state:
  cpp_type: internalstate::InternalState
  cpp_include: runnables/internal_state.hpp
